* PROBLEMA DE PROGRAMACION LINEAL
* ANALISIS DE SENSIBILIDAD - EJERCICIO EN CLASE
VARIABLES
F;
POSITIVE VARIABLES
X1, X2, X3;
EQUATIONS
OBJ, B1, B2;
OBJ.. F =E= 3*X1 + 4*X2 + (3/2)*X3;
B1.. 1*X1 + 2*X2 =L= 10;
B2.. 2*X1 + 2*X2 + 1*X3 =L= 10;
MODEL EJERCICIO /ALL/;
OPTION LP = CPLEX;
EJERCICIO.DICTFILE = 4;
EJERCICIO.OPTFILE =1;
SOLVE EJERCICIO USING LP MAXIMIZING F;
